# values.yaml

# Horizontal Pod Autoscaler (HPA) configuration
hpa:
  enabled: true
  minPods: 2            # Minimum number of pods
  maxPods: 10           # Maximum number of pods
  targetCPUUtilization: 80  # Target CPU utilization percentage

# Resource requests and limits for the application
resources:
  requests:
    cpu: "500m"          # CPU request (millicores)
    memory: "512Mi"      # Memory request (MiB)
  limits:
    cpu: "1"             # CPU limit (core)
    memory: "1024Mi"     # Memory limit (MiB)
